name: Django
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"

jobs:
  pytest:
    name: Test Django
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Setup
        run: |
          pip install pipenv
          make setup-dev
      - name: Run Tests
        run: make test

  check-django-configuration:
    name: Check Django Configuration
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Setup
        run: |
          sudo apt-get install -y pwgen
          pip install pipenv
          make setup
      - name: Test Django Configured Correctly
        run: make check-django
