name: JSON
on:
  pull_request:
    branches:
      - "*"
  push:
    paths:
      - "**/*.json"
      - ".github/workflows/json.yaml"
      - "Makefile"

jobs:
  lint-json:
    name: Lint JSON
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Setup
        run: npm install prettier@`cat package-lock.json | jq ".dependencies.prettier.version" --raw-output`
      - name: Lint JSON
        run: make lint-json
