name: YAML
on:
  pull_request:
    branches:
      - "*"
  push:
    paths:
      - "**/*.yaml"
      - "Makefile"

jobs:
  lint-yaml:
    name: Lint YAML
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Setup
        run: npm ci
      - name: Lint YAML
        run: make lint-yaml
